// <auto-generated />
namespace StudentManagement_ASP.NET_MCV5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SubjectUpdateFlagIsDeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubjectUpdateFlagIsDeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201905291709144_Subject-UpdateFlagIsDeleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
